# Generated by Django 2.2.5 on 2019-10-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frameobjectdata',
            name='object',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Object',
        ),
    ]
