# Generated by Django 2.2.6 on 2019-10-20 07:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191020_0435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('redirect_link', models.TextField()),
                ('category', models.TextField(choices=[('Sports', 'Sports'), ('Kids', 'Kids'), ('News', 'News'), ('Politics', 'Politics'), ('Music', 'Music')])),
                ('object', models.TextField()),
                ('image_link', models.TextField()),
            ],
        ),
    ]
